### PR TITLE
- Adding YOLO to Scatter

### PR DESCRIPTION
**Pull request by hernanarber**

### CODE REVIEW

**Comment by ramijames** [comment]
Can you please pull and re-commit. Dapps got removed and your version is not up to date.

**Comment by nsjames** [comment]
This is missing the image file. 
Please add a commit with a `yoloswap.com.svg` file into this PR, or remove the `"hasimage":1` property.

**Comment by ramijames** [comment]
Please re PR with the SVG image

**Comment by hernanarber** [comment]
Are these Good ENough?
[image: Yolo_logo_2.png]
[image: Yolo_logo_3.png]
[image: Yolo_logo_250.png]
<https://about.me/hernanarber?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
Hernan Arber
about.me/hernanarber
<https://about.me/hernanarber?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by ramijames** [comment]
It has to be part of the pull request. :)

**Pull request closed without merging**
