### PR TITLE
Add TronVegas

### PR DESCRIPTION
**Pull request by sandboxgames**

### CODE REVIEW

**Comment by ramijames** [comment]
I didn't see that you can actually log in with Scatter, only Tronlink.

**Comment by sandboxgames** [comment]
> I didn't see that you can actually log in with Scatter, only Tronlink.
sorry, i have thought  it should be reviewed firstly before developing. I will add scatter login to the web in few days.

**Comment by ramijames** [comment]
Nope. Please add Scatter support and I'll approve your dapp. Looks nice, by the way.

**Comment by nsjames** [comment]
Closing this for now as it has conflicts, please re-PR when ready.

**Pull request closed without merging**
