### PR TITLE
Request to add a pokerchained.com dapp

### PR DESCRIPTION
**Pull request by ruslansalikhov**

### CODE REVIEW

**Comment by ramijames** [comment]
http://www.pockerchained.com/ does not load for me

**Comment by ruslansalikhov** [comment]
Bad commit comment - pokerchained.com

**Comment by ruslansalikhov** [comment]
> http://www.pockerchained.com/ does not load for me

Address in json and pull request is correct. Just wrong commit comment

**Comment by ruslansalikhov** [comment]
Let me recreate - for clean history :)

**Pull request closed without merging**
