### PR TITLE
Add Se7en Game

### PR DESCRIPTION
**Pull request by Se7ensEOS**

### CODE REVIEW

**Comment by Se7ensEOS** [comment]
Hi thank you very much for adding us.

We are getting a lot of messages from users that are receiving an  
error when trying to claim with Scatter Desktop ver 9.2.0
Do we need to change something in our end or can you help us with this?

Thank you

Quoting Rami James <notifications@github.com>:

**Comment by ramijames** [comment]
@nsjames might be able to help you. Have you updated sdk?

**Comment by ramijames** [comment]
Also you should go to the Telegram group ScatterDevelopers. They might be able to help.

**Comment by nsjames** [comment]
Please move this ticket to [ScatterDesktop](https://github.com/GetScatter/ScatterDesktop/). 

Also please join the telegram group as Rami suggested. 
https://t.me/ScatterDevelopers

**Pull request merged**
