### PR TITLE
tronblock

### PR DESCRIPTION
**Pull request by alenmoon**
added tronblock

### CODE REVIEW

**Comment by nsjames** [comment]
I can't seem to get the "Start" button to work, and don't see any historical transactions there so might not be the only one. Going to close this for now as it seems the app isn't ready yet.

**Comment by alenmoon** [comment]
It's actually working on Chrome with Scatter. Please visit https://block.tronlegacy.org and try again.

**Comment by nsjames** [comment]
Seems like I might just be getting errors then.

image

**Comment by alenmoon** [comment]
We just did a little update, please try again at www.tronlegacy.org

**Comment by ramijames** [comment]
It is still throwing errors in Firefox

screen shot 2018-12-20 at 11 15 33 am

**Comment by nsjames** [comment]
image

While it does work with Chrome, if a user declines the transaction then it locks up after not catching the rejection and you can't click "START" again.

**Pull request closed without merging**
