### PR TITLE
update

### PR DESCRIPTION
**Pull request by shareven**
update

### CODE REVIEW

**Comment by nsjames** [comment]
Is this running on a proprietary network?
It seems Scatter is throwing errors that I don't have the network:

image


Also, what is this? :) Looks interesting.

**Comment by shareven** [comment]
running on this network:
jungle2.cryptolions.io

chain id：
e70aaab8997e1dfce58fbfac80cbbb8fecec7b99cf982a9444273cbc64c41473

image

**Comment by nsjames** [comment]
Alright, so you're going to want to issue a `scatter.suggestNetwork(network)` call before logging in. That way it will automatically suggest the network to Scatter in the case that they don't have it.

**Comment by shareven** [comment]
I have added the suggestNetwork() ;
image

**Comment by shareven** [comment]
thanks ;this link will tell u what we do. [click](https://www.poseidonplan.com/en/)

**Comment by nsjames** [comment]
Very cool 👍

**Comment by nsjames** [comment]
You should change the "Mining" section away from the extension images. Our extension has been deprecated for around 6 months. Desktop is king now.

**Comment by shareven** [comment]
we wil updade this part soon

**Pull request merged**
