### PR TITLE
Add first WAX DApp betpink.gg

### PR DESCRIPTION
**Pull request by DoNotClick**
betpink.gg is a WAX gambling site which provides a lucky wheel gamemode and is based on the bankroll dapp of https://pink.network . The complete site runs on the blockchain and is 100% provably fair.

### CODE REVIEW

**Comment by ramijames** [comment]
The logo needs to be named correctly, "betpink.gg.svg"

**Comment by DoNotClick** [comment]
> The logo needs to be named correctly, "betpink.gg.svg"

@ramijames  It is named like this. I only did it wrong in the first commit but it is correct in the latest one

**Comment by nsjames** [comment]
Please revert the WAX blockchain commit. 
WAX isn't a blockchain, it's a network which is based on the EOSIO blockchain.

**Comment by DoNotClick** [comment]
> Please revert the WAX blockchain commit.
> WAX isn't a blockchain, it's a network which is based on the EOSIO blockchain.

@nsjames the support told us to do so, but I have reverted it now!

**Comment by DoNotClick** [comment]
I also resolved the merge conflict in my last commit

**Comment by nsjames** [comment]
I'm merging this in. You should catch the "User does not have this network in their Scatter" and suggest that the user goes and sets up a WAX account. Normally I'd suggest just doing `ScatterJS.suggestNetwork()` but since WAX has a proprietary account creation system you might have to forward them to the WAX dashboard.

**Pull request merged**
