### PR TITLE
Add  coin box dapp

### PR DESCRIPTION
**Pull request by fogmoon**
Add  coin box dapp & fix the comment typos.

### CODE REVIEW

**Comment by nsjames** [comment]
Hmm the coinbox.trustdice.win URL doesn't seem to work for me.

image

**Comment by fogmoon** [comment]
@nsjames 

So sorry for my stupid which waste your valuable time. It's a tough day and I forgot some test things.

Now [coinbox.trustdice.win](https://coinbox.trustdice.win) works well. 🍹

**Comment by nsjames** [comment]
Mm, can you take off the referrer? We actually already append those in the backend.

**Comment by fogmoon** [comment]
> Mm, can you take off the referrer? We actually already append those in the backend.
Of course. ☕️

**Pull request merged**
