### PR TITLE
Added mycryptovegas.io

### PR DESCRIPTION
**Pull request by oliverne**
Most Exciting, Fun and Top Quality Casino Games in EOS World!

### CODE REVIEW

**Comment by nsjames** [comment]
I can't seem to connect with Scatter. 
Does it use ScatterJS?

**Comment by oliverne** [comment]
Absolutely.
Top, right and red 'Login' button on https://mycryptovegas.io,
that is 'connecting with Scatter'

**Comment by oliverne** [comment]
We added the Scatter logo (with get-scatter.com link) side by side login button on our site.
Please review my commits again. Thank you.

**Comment by ramijames** [comment]
Please re-PR so we can merge with apps.json

**Pull request closed without merging**
