### PR TITLE
BlockchainCuties game

### PR DESCRIPTION
**Pull request by kindex**
Added BlockchainCuties game for EOS

### CODE REVIEW

**Comment by nsjames** [comment]
applink should be `blockchaincuties.com`, please change and I'll merge.

**Comment by nsjames** [comment]
@kindex any update on this?

**Comment by kindex** [comment]
Fixed. Soory, only now I have noticed you email.

2018-12-19 08:21, Nathan James пишет:

**Comment by nsjames** [comment]
@kindex fyi there's a login-stopping bug there:

image

port must be a numerical (443) and can't be an empty string

**Comment by nsjames** [comment]
Also, in general you don't need to suggestNetwork for mainnet, it's a default network in Scatter already and will always return `true`

**Pull request merged**
