### PR TITLE
add dapp gemcity

### PR DESCRIPTION
**Pull request by gemcityio**
Submit dapp gemcity Please help me merge Thank you!

### CODE REVIEW

**Comment by ramijames** [comment]
Ahhh why isn't this awesome game in English??

**Comment by ramijames** [comment]
I could not get the game to run on Mac OS X and firefox or chrome.

**Comment by ramijames** [comment]
screen shot 2019-01-24 at 1 22 45 am

**Comment by gemcityio** [comment]
We have fixed this issue.Please help me merge Thank you!

**Pull request merged**
